### ISSUE TITLE
pymysql.err.InterfaceError when using DataJoint in debug mode

### ISSUE THREAD

**Issue by mjlm** [datajoint/datajoint-python#435] opened 2018-01-16 16:44 UTC
Hi,

Whenever I try to access a DataJoint relation while I am in the debug mode of PyCharm, I get the error below. 

Specifically, I get the error the **second** time I execute a DataJoint query at the prompt during debugging.

So it looks like DataJoint starts some MySQL query, but it does not finish properly, so that an error is thrown on the next query.

This does not happen when I am not in debug mode (i.e. just executing code at the Python console).

This happened on DataJoint 0.8 and still happens after upgrading to 0.10.

I tried executing `dj.conn().is_connected` to reset the connection, but that did not help.

It would be great to get a quick workaround for the issue...is there a command that just resets the MySQL connections?

Thanks!

```
Traceback (most recent call last):
  File "C:\Users\Matthias\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-f2ad432fc62f>", line 1, in <module>
    fit_qual = (cnn.SnPrediction.ActivityTrace() & {'run_id': current_run_id}).proj('pred_fit_qual').fetch()
  File "C:\Users\Matthias\Anaconda3\lib\site-packages\datajoint\relational_operand.py", line 257, in __and__
    if self.heading.expressions and not isinstance(self, GroupBy)
  File "C:\Users\Matthias\Anaconda3\lib\site-packages\datajoint\base_relation.py", line 45, in heading
    self._heading.init_from_database(self.connection, self.database, self.table_name)
  File "C:\Users\Matthias\Anaconda3\lib\site-packages\datajoint\heading.py", line 135, in init_from_database
    table_name=table_name, database=database), as_dict=True).fetchone()
  File "C:\Users\Matthias\Anaconda3\lib\site-packages\datajoint\connection.py", line 133, in query
    cur.execute(query, args)
  File "C:\Users\Matthias\Anaconda3\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "C:\Users\Matthias\Anaconda3\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "C:\Users\Matthias\Anaconda3\lib\site-packages\pymysql\connections.py", line 859, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "C:\Users\Matthias\Anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
```

**Comment by mjlm** [comment] 2018-01-30 19:55
Thanks for adding this to the next milestone. In the meantime, is there a quick workaround? E.g. is there a command to completely reset/restart datajoint (without re-starting the python kernel)?

**Comment by ixcat** [comment] 2018-01-30 20:13
Hello -
While I can't comment on what @dimitri-yatsenko is proposing to modify for the future release,
In the current code we don't try to support recovery for severe errors like this - you might try to reload the datajoint module (to clear internal state) and reload your datajoint related code (to update ```@schema```, etc) , but unfortunately this is usually just as complicated as a full session restart and so is not a supported approach. For debugging, when feasible, I typically create a small test script to speed up the run-debug-restart cycle for such cases.

```
from importlib import reload
reload(datajoint)
...
```

**Comment by dimitri-yatsenko** [comment] 2018-10-22 21:44
Hmm..  If the connection has been lost, then it is tough to decide what to do.   After disconnecting, the ongoing transaction is rolled back, so the state of the database may no longer be consistent.  If you run into an error that disconnects from the database, then the best thing is to rerun the computation from the start.

**Comment by dimitri-yatsenko** [comment] 2018-11-27 17:48
Since we cannot reproduce this, I am closing.  Please re-open if this problems persists.

**Closed by dimitri-yatsenko** 2018-11-27 17:48 UTC
Labels: bug
