### ISSUE TITLE
DJ Config Validation

### ISSUE THREAD

**Issue by peabody124** [datajoint/datajoint-python#442] opened 2018-01-30 22:53 UTC
I've found a few references to using this file, but it's not very well documented how to format it. 

https://github.com/datajoint/datajoint-addons/blob/master/doc/dj_local_conf.json seems relevant :)

**Comment by dimitri-yatsenko** [comment] 2018-02-13 16:17
This file is not meant to be edited manually.  The `config` object has the `save_local()` and `save_global()` methods for wirting its contents into a file and it's read automatically.  I would suggest changing the config values in Python and saving it using these methods.  However, yes, let's keep the issue open until we can point to a clear doc page that explains this.

**Comment by guzman-raphael** [comment] 2020-04-22 18:09
Adding documentation related issue in https://github.com/datajoint/datajoint-docs/issues/234 and utilizing this issue to address `dj.config` error validation.

**Comment by guzman-raphael** [comment] 2020-04-22 18:12
Duplicate of #561. Closing...

**Closed by guzman-raphael** 2020-04-22 18:12 UTC
