### ISSUE TITLE
Assertion error triggered when fetching from table with blob entries

### ISSUE THREAD

**Issue by lukerogerson** [datajoint/datajoint-python#210] opened 2016-05-28 13:49 UTC
Info: Python 3.4, latest Datajoint version. Running within a Jupyter notebook.

I have a table, defined as follows:

----------------------------------------------------------------------------------------------------------------------------
```
@schema
class Recording(dj.Manual): 
    definition="""
    # Info about a recording for a particular field. Typically corresponding to one stimuli.
    
    -> Field
    
    recording_id                :tinyint                        # integer id of recording
    ---
    wparamsnum                  :longblob                       # scan configuration info values
    os_parameters               :longblob                       # parameters used in preprocessing script
    stimulus                    :varchar(255)                   # Name of stimulus presented during recording
    triggertimes                :longblob                       # numerical array of stimulus triggers 
    wdatach0                    :longblob                       # Raw data from first channel
    wdatach1                    :longblob                       # Raw data from second channel
    wdatach2                    :longblob                       # Raw data from third channel, not currently in use
    """

```
----------------------------------------------------------------------------------------------------------------------------

For testing, I just insert an entry with only the primary key and stimulus specified. When trying to Fetch the data after inserting an entry (with `Recording().fetch()`), the following error is returned:

----------------------------------------------------------------------------------------------------------------------------
```
/usr/local/lib/python3.4/dist-packages/datajoint/fetch.py in __call__(self, **kwargs)
    162             ret = np.array(list(cur.fetchall()), dtype=heading.as_dtype)
    163             for blob_name in heading.blobs:
--> 164                 ret[blob_name] = list(map(unpack, ret[blob_name]))
    165 
    166         return ret

/usr/local/lib/python3.4/dist-packages/datajoint/blob.py in unpack(blob)
    238         return None
    239 
--> 240     return BlobReader(blob).unpack()
    241 

/usr/local/lib/python3.4/dist-packages/datajoint/blob.py in unpack(self)
     65     def unpack(self):
     66         self.decompress()
---> 67         blob_format = self.read_string()
     68         if blob_format == 'mYm':
     69             return self.read_mym_data(n_bytes=-1)

/usr/local/lib/python3.4/dist-packages/datajoint/blob.py in read_string(self, advance)
    175         """
    176         target = self._blob.find(b'\0', self.pos)
--> 177         assert target >= self._pos
    178         data = self._blob[self._pos:target]
    179         if advance:

AssertionError: 
```
----------------------------------------------------------------------------------------------------------------------------

I initially had this error on what I discovered to be an out of date copy of Datajoint. The error then was slightly different, maybe relevant to working out what went wrong:

----------------------------------------------------------------------------------------------------------------------------
```
/usr/local/lib/python3.4/dist-packages/datajoint/fetch.py in __call__(self, **kwargs)
    160             ret = np.array(list(cur.fetchall()), dtype=heading.as_dtype)
    161             for blob_name in heading.blobs:
--> 162                 ret[blob_name] = list(map(unpack, ret[blob_name]))
    163 
    164         return ret

/usr/local/lib/python3.4/dist-packages/datajoint/blob.py in unpack(blob)
     81         assert len(blob) == blob_length
     82 
---> 83     blob_type = blob[4]
     84     if blob_type != 65:  # TODO: also process structure arrays, cell arrays, etc.
     85         raise DataJointError('only arrays are currently allowed in blobs')

IndexError: index out of range
```
----------------------------------------------------------------------------------------------------------------------------

Am I using fetch incorrectly, or is something else likely to be the root of the problem? When including one of the blobs, the entering of the data still does not return an error, but subsequent attempts to fetch the entry return the error above. Dropping the tables and re-entering the record does not prevent the problem.

**Comment by dimitri-yatsenko** [comment] 2016-05-29 03:22
Would you please provide your insert statement.  I am not sure if we have tested NULLs extensively yet.  It may be the case that we not handling null values correctly.

**Comment by lukerogerson** [comment] 2016-05-29 13:20
The insert statement is:
```
recording_entries = {
   'field_id': 1,
   'recording_id': 1,
   'stimulus': 'step',
}

Recording().insert1(recording_entries)
```

Where 'field_id' is the primary key of the Field() table on which the Recording() table depends.

**Comment by dimitri-yatsenko** [comment] 2016-05-29 18:33
@eywalker: what this looks like is that Blob does not handle NULLs correctly.  Let's fix this asap.

@lukerogerson: Technically, the way you specified the table, NULLs are not allowed: you need to specify values for all fields when inserting.  MySQL should have given an error upon insert if any of the nonnullable attributes are missing but it may have settings that provide default values for missing attributes.  Please specify all attributes.  If some attributes are not applicable, they belong in a different table, most likely with the same primary key.

**Comment by dimitri-yatsenko** [comment] 2016-06-13 16:41
We cannot reproduce this problem.  It was probably caused by the MySQL server to accept inserts with missing attributes when no default was provided.  We will add more tests to make sure that a meaningful exception is raised when an incomplete insert is attempted.

Please read the new tutorials on https://github.com/datajoint/datajoint-python and let us know if problems persist.  Otherwise, I will close this issue in a few days.

**Comment by dimitri-yatsenko** [comment] 2016-06-15 17:04
I have tested a similar design and could not reproduce the problem. Please re-open if you can reproduce in version 0.2.3 or later.

**Closed by dimitri-yatsenko** 2016-06-15 17:04 UTC
Labels: invalid
