### ISSUE TITLE
aggr error

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#484] opened 2018-08-20 19:32 UTC
```python
dj.U().aggr(ta3.Segment.aggr(nda2.Trace, n='count(*)'), m='avg(n)')
```

---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/usr/local/lib/python3.6/dist-packages/IPython/lib/pretty.py in pretty(self, obj)
    398                         if cls is not object \
    399                                 and callable(cls.__dict__.get('__repr__')):
--> 400                             return _repr_pprint(obj, self, cycle)
    401 
    402             return _default_pprint(obj, self, cycle)

/usr/local/lib/python3.6/dist-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    693     """A pprint that just redirects to the normal repr function."""
    694     # Find newlines and replace them with p.break_()
--> 695     output = repr(obj)
    696     for idx,output_line in enumerate(output.splitlines()):
    697         if idx:

/usr/local/lib/python3.6/dist-packages/datajoint/relational_operand.py in __repr__(self)
    346 
    347     def __repr__(self):
--> 348         return super().__repr__() if config['loglevel'].lower() == 'debug' else self.preview()
    349 
    350     def preview(self, limit=None, width=None):

/usr/local/lib/python3.6/dist-packages/datajoint/relational_operand.py in preview(self, limit, width)
    371                 for f in columns) for tup in tuples) +
    372             ('\n   ...\n' if has_more else '\n') +
--> 373             (' (%d tuples)\n' % len(rel) if config['display.show_tuple_count'] else ''))
    374 
    375     def _repr_html_(self):

/usr/local/lib/python3.6/dist-packages/datajoint/relational_operand.py in __len__(self)
    474             ' FROM {from_}{where}'.format(
    475                 from_=self.from_clause,
--> 476                 where=self.where_clause)).fetchone()[0]
    477 
    478     def __bool__(self):

/usr/local/lib/python3.6/dist-packages/datajoint/connection.py in query(self, query, args, as_dict, suppress_warnings)
    133                     # suppress all warnings arising from underlying SQL library
    134                     warnings.simplefilter("ignore")
--> 135                 cur.execute(query, args)
    136 
    137         except err.OperationalError as e:

/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py in execute(self, query, args)
    168         query = self.mogrify(query, args)
    169 
--> 170         result = self._query(query)
    171         self._executed = query
    172         return result

/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py in _query(self, q)
    326         self._last_executed = q
    327         self._clear_result()
--> 328         conn.query(q)
    329         self._do_get_result()
    330         return self.rowcount

/usr/local/lib/python3.6/dist-packages/pymysql/connections.py in query(self, sql, unbuffered)
    514                 sql = sql.encode(self.encoding, 'surrogateescape')
    515         self._execute_command(COMMAND.COM_QUERY, sql)
--> 516         self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    517         return self._affected_rows
    518 

/usr/local/lib/python3.6/dist-packages/pymysql/connections.py in _read_query_result(self, unbuffered)
    725         else:
    726             result = MySQLResult(self)
--> 727             result.read()
    728         self._result = result
    729         if result.server_status is not None:

/usr/local/lib/python3.6/dist-packages/pymysql/connections.py in read(self)
   1064     def read(self):
   1065         try:
-> 1066             first_packet = self.connection._read_packet()
   1067 
   1068             if first_packet.is_ok_packet():

/usr/local/lib/python3.6/dist-packages/pymysql/connections.py in _read_packet(self, packet_type)
    681 
    682         packet = packet_type(buff, self.encoding)
--> 683         packet.check_error()
    684         return packet
    685 

/usr/local/lib/python3.6/dist-packages/pymysql/protocol.py in check_error(self)
    218             errno = self.read_uint16()
    219             if DEBUG: print("errno =", errno)
--> 220             err.raise_mysql_exception(self._data)
    221 
    222     def dump(self):

/usr/local/lib/python3.6/dist-packages/pymysql/err.py in raise_mysql_exception(data)
    107         errval = data[3:].decode('utf-8', 'replace')
    108     errorclass = error_map.get(errno, InternalError)
--> 109     raise errorclass(errno, errval)

InternalError: (1054, "Unknown column '' in 'field list'")

---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

/usr/local/lib/python3.6/dist-packages/datajoint/relational_operand.py in _repr_html_(self)
    457                     for name in heading.names])
    458                  for tup in tuples]),
--> 459             count=('<p>%d tuples</p>' % len(rel)) if config['display.show_tuple_count'] else '')
    460 
    461     def make_sql(self, select_fields=None):

/usr/local/lib/python3.6/dist-packages/datajoint/relational_operand.py in __len__(self)
    474             ' FROM {from_}{where}'.format(
    475                 from_=self.from_clause,
--> 476                 where=self.where_clause)).fetchone()[0]
    477 
    478     def __bool__(self):

/usr/local/lib/python3.6/dist-packages/datajoint/connection.py in query(self, query, args, as_dict, suppress_warnings)
    133                     # suppress all warnings arising from underlying SQL library
    134                     warnings.simplefilter("ignore")
--> 135                 cur.execute(query, args)
    136 
    137         except err.OperationalError as e:

/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py in execute(self, query, args)
    168         query = self.mogrify(query, args)
    169 
--> 170         result = self._query(query)
    171         self._executed = query
    172         return result

/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py in _query(self, q)
    326         self._last_executed = q
    327         self._clear_result()
--> 328         conn.query(q)
    329         self._do_get_result()
    330         return self.rowcount

/usr/local/lib/python3.6/dist-packages/pymysql/connections.py in query(self, sql, unbuffered)
    514                 sql = sql.encode(self.encoding, 'surrogateescape')
    515         self._execute_command(COMMAND.COM_QUERY, sql)
--> 516         self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    517         return self._affected_rows
    518 

/usr/local/lib/python3.6/dist-packages/pymysql/connections.py in _read_query_result(self, unbuffered)
    725         else:
    726             result = MySQLResult(self)
--> 727             result.read()
    728         self._result = result
    729         if result.server_status is not None:

/usr/local/lib/python3.6/dist-packages/pymysql/connections.py in read(self)
   1064     def read(self):
   1065         try:
-> 1066             first_packet = self.connection._read_packet()
   1067 
   1068             if first_packet.is_ok_packet():

/usr/local/lib/python3.6/dist-packages/pymysql/connections.py in _read_packet(self, packet_type)
    681 
    682         packet = packet_type(buff, self.encoding)
--> 683         packet.check_error()
    684         return packet
    685 

/usr/local/lib/python3.6/dist-packages/pymysql/protocol.py in check_error(self)
    218             errno = self.read_uint16()
    219             if DEBUG: print("errno =", errno)
--> 220             err.raise_mysql_exception(self._data)
    221 
    222     def dump(self):

/usr/local/lib/python3.6/dist-packages/pymysql/err.py in raise_mysql_exception(data)
    107         errval = data[3:].decode('utf-8', 'replace')
    108     errorclass = error_map.get(errno, InternalError)
--> 109     raise errorclass(errno, errval)

InternalError: (1054, "Unknown column '' in 'field list'")

**Comment by dimitri-yatsenko** [comment] 2018-08-20 20:56
apparently this has been introduced in `0.10.0`.  Need to add regression tests to catch this.

**Comment by eywalker** [comment] 2018-12-02 14:40
This should be addressed in the next release.

**Comment by guzman-raphael** [comment] 2019-11-18 17:42
@dimitri-yatsenko is #604 a duplicate of this?

**Closed** 2021-03-24 07:01 UTC
Labels: bug
