### ISSUE TITLE
Parents not correctly detected during import

### ISSUE THREAD

**Issue by ecobost** [datajoint/datajoint-python#441] opened 2018-01-30 02:26 UTC
```python
In [1]: from stimline import tune
Loading local settings from pipeline_config.json
Connecting ecobost@10.28.3.113:3306
/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py:165: Warning: (1681, "'ERROR_FOR_DIVISION_BY_ZERO' is deprecated and will be removed in a future release.")
  result = self._query(query)
/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py:165: Warning: (1681, "'NO_ZERO_DATE' is deprecated and will be removed in a future release.")
  result = self._query(query)
/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py:165: Warning: (1681, "'NO_ZERO_IN_DATE' is deprecated and will be removed in a future release.")
  result = self._query(query)
 
In [2]: tune.STA().parents()
Out[2]: {}

In [3]: tune.STA().populate({'animal_id': 238282929})

In [4]: tune.STA().parents()
Out[4]: 
{'`pipeline_fuse`.`__activity`': {'aliased': False,
  'attr_map': {'animal_id': 'animal_id',
   'channel': 'channel',
   'field': 'field',
   'pipe_version': 'pipe_version',
   'scan_idx': 'scan_idx',
   'segmentation_method': 'segmentation_method',
   'session': 'session',
   'spike_method': 'spike_method'},
  'multi': True,
  'primary': True},
 '`pipeline_stimulus`.`_sync`': {'aliased': False,
  'attr_map': {'animal_id': 'animal_id',
   'scan_idx': 'scan_idx',
   'session': 'session'},
  'multi': True,
  'primary': True},
 '`pipeline_tune`.`#stimulus_type`': {'aliased': False,
  'attr_map': {'stimulus_type': 'stimulus_type'},
  'multi': True,
  'primary': True}}
```

In this example, tune.STA().populate() worked fine but it fails  under some odd circumstances, e.g., :
```
from pipeline import fuse, treadmill
treadmill.Treadmill().populate({'animal_id': 238282929})
from stimline import tune
tune.STA().populate({'animal_id': 238282929})

That gives this error:
---------------------------------------------------------------------------
DataJointError                            Traceback (most recent call last)
<ipython-input-4-b4b18d592aeb> in <module>()
      3 
      4 from stimline import tune
----> 5 tune.STA().populate({'animal_id': 238282929})

/usr/local/lib/python3.5/dist-packages/datajoint/autopopulate.py in populate(self, suppress_errors, reserve_jobs, order, limit, max_calls, display_progress, *restrictions)
    111             old_handler = signal.signal(signal.SIGTERM, handler)
    112 
--> 113         keys = (self._jobs_to_do(restrictions) - self.target).fetch("KEY", limit=limit)
    114         if order == "reverse":
    115             keys.reverse()

/usr/local/lib/python3.5/dist-packages/datajoint/autopopulate.py in _jobs_to_do(self, restrictions)
     70         :return: the relation containing the keys to be computed (derived from self.key_source)
     71         """
---> 72         todo = self.key_source
     73         if not isinstance(todo, RelationalOperand):
     74             raise DataJointError('Invalid key_source value')

/data/stimulus-pipeline/python/stimline/tune.py in key_source(self)
    825     def key_source(self):
    826         return (super().key_source &
--> 827                 "stimulus_type in ({conds})".format(conds=','.join("'%s'" % r for r in self.conditions)) &
    828                 stimulus.Trial() * stimulus.Condition())
    829 

/usr/local/lib/python3.5/dist-packages/datajoint/autopopulate.py in key_source(self)
     37             parents = list(self.target.parents(primary=True))
     38             if not parents:
---> 39                 raise DataJointError('A relation must have parent relations to be able to be populated')
     40             self._key_source = FreeRelation(self.connection, parents.pop(0)).proj()
     41             while parents:

DataJointError: A relation must have parent relations to be able to be populated
``` 
Code for `tune` is [here](https://github.com/ecobost/stimulus-pipeline/blob/8e218fe95d334917ee98081712d3a23d89599aa1/python/stimline/tune.py) (private repo)

**Comment by dimitri-yatsenko** [comment] 2018-10-17 14:58
Are you still able to reproduce this error?  I would like to debug this.

**Comment by ecobost** [comment] 2018-10-17 21:38
Second script code didn't fail anymore. It still has empty parents after importing, though.

**Comment by guzman-raphael** [comment] 2021-01-19 17:34
@ecobost Could you provide more specific details on how to consistently reproduce this issue? Otherwise we may need to close this as there is not enough info to verify a fix.

**Comment by guzman-raphael** [comment] 2021-01-25 17:30
@ecobost Closing due to inactivity but feel free to reopen if necessary.

**Closed by guzman-raphael** 2021-01-25 17:30 UTC
Labels: bug, needs-discussion
