### ISSUE TITLE
Dataset transfer

### ISSUE THREAD

**Issue by ttngu207** [datajoint/datajoint-python#791] opened 2020-05-26 14:08 UTC
Related to Issue #560 
DataJoint needs a feature to select a subset of data to be transferred to another database (with identical scheme/pipeline design)
For instance, users would select particular session(s) and all relevant upstream and downstream data are to be transferred to a specified host.

**Comment by CBroz1** [comment] 2021-12-14 20:59
Relabel to `enhancement` or `under-development`?

**Comment by dimitri-yatsenko** [comment] 2022-10-07 19:50
Duplicate of #560 
We will address these together.

**Closed by dimitri-yatsenko** 2022-10-07 19:50 UTC
Labels: needs-discussion
