### ISSUE TITLE
np.float32 not supported for longblobs yet

### ISSUE THREAD

**Issue by Synicix** [datajoint/datajoint-python#572] opened 2019-03-15 07:31 UTC
I was attempting to shove a numpy array of FP32 values and datajoint complained that it is not supported yet.

Error message:
packing object of type <class 'numpy.float32'> currently not supported!

I got around it by converting it to np.float which is equivalent to np.float64, but that will be taking up double the space.

Is this a feature that is going be implemented later? Also will there be support for other datatypes such as np.float16?

**Comment by dimitri-yatsenko** [comment] 2019-03-15 10:36
DataJoint the storage of both scalar values of single precision values in attributes of type `float` and numerical arrays of `float32` in blobs. 

Could you provide the snippet of the insert code to reproduce the problem?

**Comment by dimitri-yatsenko** [comment] 2019-03-15 10:58
float32 blob serialization is tested explicitly in https://github.com/datajoint/datajoint-python/blob/f41d474e395f823773ab01c5034191784f2293e2/tests/test_blob.py#L17 and works reliably

**Comment by dimitri-yatsenko** [comment] 2019-03-19 18:18
DataJoint maintains interoperability between MATLAB and Python.  MATLAB lacks the concept of a scalar or a 1D vector: any number is a 1x1 2D array.

Release 0.12.1 will allow saving all Python data types except for custom classes and objects, including issues 
* #572
* #520 
* #427 

The solution described in #520 will address all these issues.

**Comment by dimitri-yatsenko** [comment] 2019-03-20 14:58
Actually, the fix was trivial. DataJoint already supported serialization of scalars -- it just was not turned on. The fix is coming out in 0.12

**Comment by dimitri-yatsenko** [comment] 2019-03-20 15:26
This is fixed with #576.  However, scalars in blobs will come out as empty fields in datajoint-matlab because matlab lacks the concept of a scalar. We will need to modify datajoint-matlab to interpret scalars as 1x1 matrices.

**Closed** 2019-05-20 06:28 UTC
Labels: features
