### ISSUE TITLE
renamed foreign key table definition constraint issue

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#518] opened 2018-11-14 02:01 UTC
defining a renamed foreign key reference to a partial key defined in:
```@schema
class Animal(dj.Manual):
    definition = """
    animal_id : char(16)
    datasource_id=0: int
    ---
    animal_species: varchar(16)
    animal_name: varchar(128)
    animal_sex: ENUM('M', 'F', 'U')
    animal_dob=NULL: date
    -> AnimalColor
    """
```
via:
```
@schema
class Dam(dj.Manual):
    definition = """
    -> Animal
    (dam_id) -> Animal(animal_id)
    """
```
yields:
```
CREATE TABLE IF NOT EXISTS `tutorial_mlims_prod_ephys`.`dam` ( `animal_id` char(16) NOT NULL COMMENT "", `datasource_id` int NOT NULL COMMENT "", `dam_id` int NOT NULL COMMENT "", PRIMARY KEY (`animal_id`,`datasource_id`,`dam_id`), FOREIGN KEY (`animal_id`,`datasource_id`) REFERENCES `tutorial_mlims_prod_ephys`.`animal` (`animal_id`,`datasource_id`) ON UPDATE CASCADE ON DELETE RESTRICT, FOREIGN KEY (`datasource_id`,`dam_id`) REFERENCES `tutorial_mlims_prod_ephys`.`animal` (`animal_id`,`datasource_id`) ON UPDATE CASCADE ON DELETE RESTRICT ) ENGINE=InnoDB, COMMENT "";
```
and therefore this:
```pymysql.err.IntegrityError: (1215, 'Cannot add foreign key constraint')
```

#517 code resolves issue.

**Comment by ixcat** [comment] 2018-11-14 02:02
@dimitri-yatsenko - FYI filed this on @eywalker request for documentation; as mentioned #517 code seems to fix currently.

**Comment by dimitri-yatsenko** [comment] 2018-11-14 07:42
This is a duplicate of #516.  Closing.

**Comment by eywalker** [comment] 2018-11-14 13:16
Do not close when the reported error is being different. As already noted by @ixcat the underlying issue is known to be the same as in #516. Let this be closed by accepting the PR.

**Comment by dimitri-yatsenko** [comment] 2018-11-17 21:51
Closing via #517

**Closed by dimitri-yatsenko** 2018-11-17 21:51 UTC
Labels: duplicate
