### ISSUE TITLE
Cascading delete for Part

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#151] opened 2015-08-28 20:51 UTC
The cascading delete still doesn't handle the case involving `dj.Part` correctly. Basically, any deletion on `dj.Part` should cause deletion on its _parent_ table. Marking deletion on the _parent_ table then should cause appropriate cascading of deletion on the _parent's_ as well as `Part`'s subtables.

**Comment by dimitri-yatsenko** [comment] 2015-09-10 14:49
The term "subtable", as we have sometimes used it, is now replaced with "part relation". Let's also use "master relation" to indicate the relation containing the part relation.  We have also decided that part relations cannot have their own part relations.

So to restate the present issue: 
- Deleting from a part relation should not be possible without deleting matching tuples from its master relation. 

We have two options to address this issue:
1. prohibit deletes from a part relation that are not cascaded through its master relation 
2. delete from the master relation when a delete is issued on the part relation

Option 1 seems overly restrictive since a part relation may have dependencies not shared by its master and some cascading deletes may halt and force the user to break up a single delete command into several more specific commands.  If we pursue this solution, we need to make sure that the error message and the suggested course of action are clear.

Option 2 seems a bit aggressive since now deletes will cascade one level up the dependency hierarchy as well as down. This may be counterintuitive to some users.  This concern is partly addressed by displaying a summary of the data to be deleted before committing the delete.  Also option 2 may produce more complex queries that may be much slower than ones resulting from Option 1.

Which option should we choose?

**Comment by eywalker** [comment] 2015-09-10 15:52
I almost always prefer strong and convenient (but potentially destructive) solution, provided that we keep it informative. So if I have to choose, I'd prefer to use option 2. However, I also think this is a perfect opportunity for us to use config to alter between different behaviors, and offer both option 1 and option 2.

**Comment by fabiansinz** [comment] 2015-09-10 19:29
I prefer option 2 and I think we should offer to change the behavior in the config.

**Comment by dimitri-yatsenko** [comment] 2015-09-10 20:56
I support Option 2. However, making datajoint configurable between these two options would create undue documentation and testing burden. Let's implement Option 2 and document it well.

**Comment by dimitri-yatsenko** [comment] 2016-06-16 06:34
I relabeled this as a 'feature' because the current implementation acts reasonably: it fails to delete when attempting to delete from parts, bypassing the master. I just don't want panic to set in that cascading deletes are unsafe.

**Comment by mspacek** [comment] 2017-03-09 18:43
Hello! OK, so the term "subtable" is no longer used. It's crucial to update the documentation to reflect that. I just spent several hours trying to figure out how to define a subtable, including searching through the code, and finally ended up here.

Am I correct in assuming the original issue reported above by @eywalker remains? I'm trying to define a part relation, such that if I try to delete parts, I'm either not allowed to, or I am but it automatically deletes the appropriate tuples in the parent (or "master part"). At the moment, I'm not seeing either option 1 or 2 behaviour. I've followed the example I found in `datajoint.tests.schema.Ephys.Channel`. Maybe the easiest thing to do for now is to define a `delete()` method that does nothing? I've added this to my part relation:
```
        def delete(self):
            """Override self.delete() so that it does nothing other than print a message"""
            print("direct deletion from %s is disabled because it's a part relation "
                  "(subtable) of %r" % (self.__class__, self._master))
```
and it seems to work as intended.

**Comment by dimitri-yatsenko** [comment] 2017-03-10 00:08
Hi @mspacek, the master-part relationship has now been defined consistently between matlab and python and we can move quickly on the documentation.  Thank you for your patience.

Yes, this issue is still open.  The master-part relationship has not been strongly enforced.  Now you are able to delete from part without deleting from master.  This should not be done and eventually we need to enforce the master-part discipline by either Option 1 or Option 2.  I like Option 1 because it is easy to implement correctly.  Option 2 is more involved but may be more user friendly.

**Comment by dimitri-yatsenko** [comment] 2017-03-10 00:11
I propose to implement Option 1 now similar to what @mspacek did.   If we run into problems, we will create a new issue to implement Option 2.

**Comment by eywalker** [comment] 2017-03-10 01:08
Let's proceed with Option 1 for now, but plan to implement Option 2 in the future. There wouldn't be a problem per se with Option 1 but it is undoubtedly more convenient to have Option 2 available as a feature. Future transition from Option 1 -> Option 2 should cause no issue.

**Comment by eywalker** [comment] 2017-11-11 21:28
Support for this will significantly improve the usability of `Part` tables and any future extensions around this logic.

**Comment by SimonRenner** [comment] 2019-10-14 11:38
Hi guys,
judging from the earlier conversation I am not sure if you are aware of this: while direct (manual) deletes from a `Part` table fail, deletes that are caused by deleting from a referenced table will go through and delete only from `Part`, leaving `Master` orphaned. Contrary to what @dimitri-yatsenko wrote earlier I would thus conclude that cascading deletes are indeed unsafe. As I couldn't really figure out how to do properly construct the delete list from sql as it is done in the datajoint code, I tried to write a modified delete method that looks up the `Master` tables in python and performs the deletes:
`def delete_cascade(self):
        self.connection.dependencies.load()
        master_tables_of_descendants = []
        keys_to_delete = []
        for desc in self.descendants():
            desc_class_name = dj.table.lookup_class_name(desc, globals())
            desc_class_instance = eval(desc_class_name+'()')
            try:
                master_tables_of_descendants.append(desc_class_instance._master)
                keys_to_delete.append((desc_class_instance._master & self).fetch(dj.key))
            except AttributeError:
                pass
        for master, keys in zip(master_tables_of_descendants, keys_to_delete):
            (master() & keys).delete()
        self.delete()`
Perhaps something similar could already be done as a hotfix before the bug is properly fixed in a future release?

**Comment by SimonRenner** [comment] 2019-10-14 15:15
I just noticed that the same problem also exists for `drop`.

**Comment by dimitri-yatsenko** [comment] 2019-10-14 18:12
High priority for release 0.12.1

**Comment by guzman-raphael** [comment] 2019-11-18 18:37
Possibly related to #374

**Comment by dimitri-yatsenko** [comment] 2019-11-18 19:37
Yes, #374 and #151 cane be merged and addressed with a single solution.

**Comment by zfj1** [comment] 2021-09-03 18:58
I saw that this was mentioned in #934, just wondering if there's been any progress on this? I would agree with the sentiment that this fundamentally violates the "many-to-one" relationship integrity.

Option 2 seems much more user-friendly, since in the case of cascading deletes, Option 1 requires either anticipating or handling failures and deleting the problematic master/part relation before deleting the intended relation further up the dependency tree. In fact I would suggest implementing Option 1 for direct deletes from part table (i.e., can only delete directly from the master), and Option 2 for cascading deletes.

The tricky part of this seems to be that the part relation must be deleted before the master, but we need to restrict the master by the part in the case of cascading deletes, which would obviously not be possible if the part is deleted. Probably the best solution is to store the part relation in a temporary relation on the server, delete from the part table, then delete from the master using the temp relation. The suggestion above by @SimonRenner involves a fetch which I presume is slower than storing on the server, and might break down for more complex relations.

I played around with implementing this in the matlab version. The following (alternative) approach seems to work nicely:
- When deleting a relation, check whether the table is a part table.
  - If the relation is the caller (i.e., a direct delete), throw an error
  - If the relation's master is not in the caller's descendents, don't delete the relation and instead call `delete()` on the master restricted by the part-table relation
  - If the relation's master is the caller itself, don't delete directly, but instead delete alongside the caller
  - If the relation's master _is_ in the caller's descendents, then just delete the part as normal (this is the typical, working case)
- When deleting a caller that is a master:
  - Drop the foreign key constraint on the part (temporarily)
  - Perform a multi-delete: `'DELETE part,master FROM {(part * master * part_relation).make_sql()}'`
  - Re-apply the foreign key constraint
I have yet to test this on masters with multiple parts or part tables that have multiple dependencies on the master, but I think the general logic will apply

**Comment by dimitri-yatsenko** [comment] 2021-09-24 14:59
Thank you, @zfj1. The multi-table delete is probably the way to go. 

For now in #957, we took the more cautious approach of prohibiting deletes where the part is deleted without its master.

**Comment by chrisroat** [comment] 2021-09-27 22:45
I look forward to Option 2.  If several Master-Part relations are involved in a cascade, it is painful to figure out the deletes manually.  I think Option 1 at least keeps the data integrity -- but I think the pain of manual deletes is still going to be there.

**Closed** 2022-01-20 19:28 UTC
Labels: bug

**Comment by ttngu207** [comment] 2023-06-13 18:23
@dimitri-yatsenko , @guzman-raphael It appears that implementation of Option 2 is still highly desirable. 
This is currently a major pain point for the SpyGlass pipeline - see https://github.com/LorenFrankLab/spyglass/issues/469

**Comment by CBroz1** [comment] 2024-03-29 20:32
Is this issue worth reopening to track the potential feature add of Option 2?

**Comment by ttngu207** [comment] 2024-04-01 16:29
@CBroz1 I agree. 
@dimitri-yatsenko let's re-evaluate option 2 and consider a potential implementation.
