### ISSUE TITLE
restricted database dump

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#200] opened 2016-03-29 23:36 UTC
For the purpose of sharing data associated with analysis performed using DataJoint, it will be nice if there  is a way for us to make _partial_ dumps of the database. The partial dump will contain all the tables and the **relevant** table entries (tuples) that makes sense to be shared, but will not contain unrelated tuples nor tables. Furthermore, if the analysis code being shared do not depend explicitly on certain parent tables, we should be able to provide a _simplified_ schema  that do not contain those tables.

To make this happen, we must create a dump of existing database where we omit certain tables and also any foreign key constraints involving the omitted tables. The dump will contain the necessary table creation MySQL code (e.g. `CREATE TABLE IF NOT EXISTS`...) but with some/all foreign key constraints removed if the target parent/dependent table was decided to be not included. It will then be followed by appropriately restricted list of tuples to be inserted.

The third person can then simply recreate all the relevant part of the database by first loading the custom MySQL dump, and then he can use the provided code to navigate and run any analysis as allowed.

**Comment by dimitri-yatsenko** [comment] 2016-03-30 21:49
please propose a syntax

**Comment by eywalker** [comment] 2016-03-30 23:58
Let's say that we have a table listing all electrophysiology experiments called `Ephys`, and we want to  dump all data pertaining to one subject with id `subj_id = 21` as well as some of the relevant tables around the target table `Ephys`. But we don't want to include the very top tables called `Subjects` and `Animals` because they are not strictly needed to inspect the data and run analysis. I'd imagine the dump creation syntax to be something as follows:

```python
dj.dump(Ephys & 'subj_id = 21', exclude=[Subjects, Animals])
```
This can then return the MySQL dump string. `exclude` takes in a list of DataJoint classes corresponding to tables that needs to be excluded from the dump. The dump will only try to include tables and their entries that are related to the target tuples (here `Ephys & 'subj_id = 21`).

**Comment by guzman-raphael** [comment] 2019-11-18 18:31
@eywalker is #560 a duplicate of this?

**Comment by dimitri-yatsenko** [comment] 2019-11-18 19:18
yes, #560 duplicates this.

**Comment by dimitri-yatsenko** [comment] 2019-11-18 21:23
I think the implementation needs to consist of two parts:  dj.Diagram needs to have

**Comment by ixcat** [comment] 2020-04-14 23:29
replaced by #485 560

**Closed by ixcat** 2020-04-14 23:29 UTC
Labels: features
