### ISSUE TITLE
Error with`dj.Diagram()` and new release of `pydot==3.0.*`

### ISSUE THREAD

**Issue by MilagrosMarin** [datajoint/datajoint-python#1169] opened 2024-08-19 16:26 UTC
## Bug Report
One month ago, `pydot` released version 3.0, which introduced breaking changes ([reference](https://github.com/pydot/pydot/blob/24ff13d82dc8db3c14ece6ad27af1f2da27d3f68/ChangeLog#L27C1-L59C1)). These changes appear to be causing issues with `dj.Diagram`.

One of the breaking changes in the new version of `pydot` is `Breaking change: Remove .create_attribute_methods() from classes`, and the error I received breaks in `dj.Diagram` using `create_*()`.  The `datajoint-python` unit tests cover the import and table attributes but not the create attributes [reference](https://github.com/datajoint/datajoint-python/blob/5a6077fc842c1855471a91e989547704615b5f33/tests/test_erd.py#L27-L48).

Downgrading to `pydot==2.0` resolves these issues and restores plotting functionality for `dj.Diagram`.

### Description
```
dj.Diagram(probe)

{
	"name": "AssertionError",
	"message": "\"dot\" with args ['-Tsvg', '/var/folders/h8/_lx50k3d6qx586662kr066h40000gn/T/tmp2kxf9kd7'] returned code: 1",
	"stack": "---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
File ~/miniconda/envs/utah_organoids/lib/python3.10/site-packages/IPython/core/formatters.py:347, in BaseFormatter.__call__(self, obj)
    345     method = get_real_method(obj, self.print_method)
    346     if method is not None:
--> 347         return method()
    348     return None
    349 else:

File ~/miniconda/envs/utah_organoids/lib/python3.10/site-packages/datajoint/diagram.py:436, in Diagram._repr_svg_(self)
    435 def _repr_svg_(self):
--> 436     return self.make_svg()._repr_svg_()

File ~/miniconda/envs/utah_organoids/lib/python3.10/site-packages/datajoint/diagram.py:424, in Diagram.make_svg(self)
    421 def make_svg(self):
    422     from IPython.display import SVG
--> 424     return SVG(self.make_dot().create_svg())

File ~/miniconda/envs/utah_organoids/lib/python3.10/site-packages/pydot/core.py:169, in __generate_format_methods.<locals>.__create_method(self, f, prog, encoding)
    167 def __create_method(self, f=frmt, prog=None, encoding=None):
    168     \"\"\"Refer to docstring of method `create`.\"\"\"
--> 169     return self.create(format=f, prog=prog, encoding=encoding)

File ~/miniconda/envs/utah_organoids/lib/python3.10/site-packages/pydot/core.py:1825, in Dot.create(self, prog, format, encoding)
   1819     code = process.returncode
   1820     print(
   1821         f'\"{prog}\" with args {arguments} returned code: {code}\
\
'
   1822         f\"stdout, stderr:\
 {stdout_data}\
{stderr_data}\
\"
   1823     )
-> 1825 assert process.returncode == 0, (
   1826     f'\"{prog}\" with args {arguments} '
   1827     f\"returned code: {process.returncode}\"
   1828 )
   1830 return stdout_data

AssertionError: \"dot\" with args ['-Tsvg', '/var/folders/h8/_lx50k3d6qx586662kr066h40000gn/T/tmp2kxf9kd7'] returned code: 1"
}

```

### Reproducibility
- OS (MACOS)
- Python Version: 3.10
- DataJoint Version: 0.14.1
- pydot Version: 3.0.1
<img width="547" alt="Screenshot 2024-08-17 at 02 10 40" src="https://github.com/user-attachments/assets/6d5421b9-f0a4-4cac-a5f8-f6bff0b71a40">
<img width="912" alt="Screenshot 2024-08-17 at 02 23 39" src="https://github.com/user-attachments/assets/714d2bb1-d264-4037-ab95-0e33cfec03ea">
<img width="953" alt="Screenshot 2024-08-17 at 02 29 59" src="https://github.com/user-attachments/assets/d1ce6c2a-862c-4d3a-adf6-c04d0c65a8b1">

### Expected Behavior
The diagram to be plotted in the output.

### Additional Research and Context
- [pydot release 3.0 ChangeLog](https://github.com/pydot/pydot/blob/24ff13d82dc8db3c14ece6ad27af1f2da27d3f68/ChangeLog#L27C1-L59C1)
- [datajoint-python requirements](https://github.com/datajoint/datajoint-python/blob/master/requirements.txt)
- [datajoint-python tests](https://github.com/datajoint/datajoint-python/blob/5a6077fc842c1855471a91e989547704615b5f33/tests/test_erd.py#L27-L48)

**Comment by ethho** [comment] 2024-09-06 14:56
@MilagrosMarin Is this a duplicate of #1175?

**Comment by MilagrosMarin** [comment] 2024-09-06 16:41
@ethho, issue #1175 was published a few hours ago and is a duplicate of this issue #1169. The error described is the same in both, and both issues are relating the error with recent versions of `pydot` and `networkx`.

**Closed** 2024-09-09 18:33 UTC
Labels: bug

**Comment by ethho** [comment] 2024-09-09 19:23
@MilagrosMarin This should be fixed if you pip install `master` branch; re-open this issue if it is not resolved.
