### ISSUE TITLE
date data type was fetched as strings in 0.13.1 on IBL public server

### ISSUE THREAD

**Issue by shenshan** [datajoint/datajoint-python#905] opened 2021-04-20 00:32 UTC
### Description
With 0.13.1, date data type was fetched as strings in ibl public server.

### Reproducibility
I was not able to replicate it in my local mariadb, but this error was seen on ibl public database. Another difference between the two set ups is that on ibl public database, I was using python 3.8, while on local, I was using python 3.7.
![image](https://user-images.githubusercontent.com/2539832/115319617-11dd8180-a135-11eb-8701-d4004193b9e9.png)

When reverting to 0.12.9, this was gone.

**Comment by Synicix** [comment] 2021-06-04 05:05
Update on this issue:

So after digging through datajoint then pymysql then the MYSQL manuals, the underlying problem seems to be in how MYSQL version 5.7 handles `MIN(DATE(rows))` where rows would be the date column of a table. That query will result in a string return value. In version 8.0 however, the same query returns a DATE object.

Here is what MYSQL 5.7 would spit out:
![image](https://user-images.githubusercontent.com/10690095/120747868-6c555600-c4c7-11eb-9f6c-ab9c08467598.png)

And here is MYSQL 8.0 result:
![image](https://user-images.githubusercontent.com/10690095/120747914-7ecf8f80-c4c7-11eb-9caf-7707b8560973.png)

I just use datajoint to make it simple to understand, but this issue can be replicated via SQL queries.


Propose Solution:
Due to the nature of this problem, I don't think we should write a hack in datajoint to go around this. Instead a way to ensure that the final result would result in date would be to replace `MIN(DATE(rows))` with `DATE(MIN(DATE(rows))` which would give the desired date format you wanted.

![image](https://user-images.githubusercontent.com/10690095/120748208-04533f80-c4c8-11eb-8a2d-4d0d9a7424ed.png)


In your case just replace `'MIN(DATE(session_start_time))'` with `DATE(MIN(DATE(session_start_time))'` or rather if you want to be efficient about it, the query should be `'DATE(MIN(session_start_time))'` which will covert the final result to DATE without doing the DATE conversion ahead of time for all rows.

Recommend Solution example:
![image](https://user-images.githubusercontent.com/10690095/120748579-a115dd00-c4c8-11eb-9efa-e94f2c1765e7.png)

**Comment by Synicix** [comment] 2021-06-04 05:06
@guzman-raphael @shenshan If this is satisfactory solution for you guys then we can close this issue.

**Comment by shenshan** [comment] 2021-06-04 06:03
Sure I can work around with it as you suggested.

**Comment by Synicix** [comment] 2021-06-04 21:38
@shenshan Cool, I wait for @guzman-raphael to come back and decide whether to close the issue or not.

**Comment by Synicix** [comment] 2021-06-09 20:55
Did a debugging sessions with @guzman-raphael and we came up with the final report about this issue.

Though the debugging process we determine two bugs with the way MYSQL.

The first one was the one originally reported here https://github.com/datajoint/datajoint-python/issues/905#issuecomment-854361180 where doing a MIN(DATE('column_name') in MYSQL 5.7 results in a varchar, while in MYSQL 8.0 in return datetime.

The second bug was found via the follow up with @shenshan to see if it is a regression bug: https://github.com/datajoint/datajoint-python/issues/905#issuecomment-857260688

In this bug, the issue arise in MYSQL 5.7 where if the user packs the original query with the MIN(DATE('column_name')) in a subquery of another select query, such as in the case with Datajoint 0.12.9 query engine, it returns a date instead of a varchar

Due to this issue coming from MYSQL itself, our recommendation for resolving this issue is the following:

Option 1) : Upgrade to MYSQL 8.0 where the behavior is more consistent and expected
Option 2): Use a more explicit query where instead of MIN(DATE('column_name')), the recommended way should be DATE(MIN('column_name'))

**Comment by guzman-raphael** [comment] 2021-06-09 23:29
@Synicix Thanks for posting these summaries. It is unfortunate about these MySQL 5.7 bugs but that is just how it is sometimes... I'd say this issue is resolved now since the workaround provided is mainly to reduce MySQL bug impact. Not much we can do in DJ side w/o introducing much more complexity that is much too version specific.

**Closed** 2021-06-09 23:29 UTC
Labels: bug
