### ISSUE TITLE
Making ERD.draw() work

### ISSUE THREAD

**Issue by aless80** [datajoint/datajoint-python#618] opened 2019-05-29 12:06 UTC
Please consider to update your documentation so that users have higher chances of having ERD.draw work. The following description is how I made it that functionality work on my Linux Mint machine. I also propose some corrections.

I have datajoint installed in a virtual environment (which is the recommended way to install any python application). 
0) The problem: when trying to run dj.ERD(schema).draw() I got an error (AttributeError: 'ERD' object has no attribute 'draw'). Inspect dj.ERD.__doc__ and you find a message saying that you need matplotlib and pygraphviz. Notice that the link provided is dead
1) First I had to install the following packages otherwise I get the problem in point 3: 
`sudo apt-get install tcl-dev tk-dev python-tk python3-tk`
See the explanation on this [link](https://www.pyimagesearch.com/2015/08/24/resolved-matplotlib-figures-not-showing-up-or-displaying/) 
2) Install the python dependencies with `pip install -r requirements.txt`
Install matplotlib with pip in venv or with pip --user (no sudo pip)! 
`pip install matplotlib pydotplus pydot-ng graphviz`
I am not sure which of the other packages in the command above are necessary. If they are, I suggest adding them to requirements.txt
3) Notice that if I skip point 1 I cannot use draw anyway: 
```
>>> dj.ERD(schema).draw()
/home/amarin/datajoint-python/datajoint/erd.py:308: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
```
The problem is explained in the link in point 1. I add to follow point 1 above and reinstall matplotlib. In the end the following command should return TkAgg (not agg):

```
matplotlib.get_backend()
'TkAgg'
```

**Comment by guzman-raphael** [comment] 2019-05-30 16:12
Hi @aless80. Thank you for your feedback. Can you check if you have apt pkg `python3-tk` installed? 
If not, can you install it and try running your script again and update us on the result?

**Comment by guzman-raphael** [comment] 2019-05-30 18:46
Hi @aless80. Thank you for your feedback. It seems that the issue here is that DataJoint's system dependencies are not clearly documented in our documentation + matplotlib needed to be added to pip requirements. If we add a list of these system dependencies for several LNX distro's, would this satisfy your issue? PR for pip requirements to follow.

As far as system dependencies, let me give a brief overview of what it looks like for a base Alpine3.9 image. For APT, these would be quite similar.

`apk add musl-dev g++ pkgconfig gcc freetype-dev graphviz ghostscript-fonts python3-tkinter`
`pip install --user datajoint`    (once PR merged and we make a next release, this will be all that is needed)

**Comment by aless80** [comment] 2019-05-31 08:14
It sounds good
Best
AM

**Comment by aless80** [comment] 2019-05-31 09:53
Hi,
I would check that but I am going to be out of office for some time 1/2
months.
Sorry for that
Alessandro Marin

**Comment by tjd2002** [comment] 2019-06-08 23:00
If you are a conda user, you may also be interested to try out the new conda-based install method (#293).

Conda takes care of installing all the dependencies (including tk, graphviz, Matplotlib...), in an isolated environment, without the need to install any packages system-wide through apt/apk. I've confirmed it works to generate ERD's within a Jupyter Lab notebook. 

If you try it and it doesn't work as expected please open an issue and tag me.

**Comment by aless80** [comment] 2019-06-09 03:36
Hi Tom,
Thank you. Good too hear that conda works. I'm probably wrong but I never
became a fan of conda, so I'll trust you on that.
Best
A.M.

**Closed** 2019-07-02 21:20 UTC
Labels: bug
