### ISSUE TITLE
Preview Error

### ISSUE THREAD

**Issue by FedeClaudi** [datajoint/datajoint-python#515] opened 2018-11-01 19:43 UTC
Hi, 

I'm running DataJoint with Python3 on Windows with a locally hosted server. 
I reliably get an error when trying to inspect the content of a class:

Example class definition:

```
@schema
class BehaviourRecording(dj.Manual):
     definition = """
     # Individual recordings within a session
     -> Session
     recording_number: int               # recording number within a session
     ---
     metadata_path : varchar(128)       # name of the experimenter
     video_path : varchar(128)       # name of the experimenter
     tracked : enum('Y', 'N')   # asdas
     dlc_data: varchar(128)      # path to .h5 produced as a result of dlc tracking
     """
```

Example error:
```
recordings = BehaviourRecording()
recordings.preview()
Traceback (most recent call last):
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\IPython\core\interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-5ee312724859>", line 1, in <module>
    recordings.preview()
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\datajoint\relational_operand.py", line 362, in preview
    tuples = rel.fetch(limit=limit+1)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\datajoint\fetch.py", line 59, in __call__
    cur = self._relation.cursor(as_dict=as_dict, limit=limit, offset=offset, order_by=order_by)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\datajoint\relational_operand.py", line 530, in cursor
    return self.connection.query(sql, as_dict=as_dict)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\datajoint\connection.py", line 136, in query
    cur.execute(query, args)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
```

Any idea how to solve this? I can work around it using fetch, but it makes things more complicated.

Thank you!

**Comment by dimitri-yatsenko** [comment] 2018-11-02 04:07
hm.. I couldn't reproduce.   Was the database connection lost?  Can you try restarting the kernel and re-running the code?  Also, would you upgrade to the latest version: datajoint 0.11.0?

**Comment by dimitri-yatsenko** [comment] 2018-11-02 04:07
I would like to be able to re-produce this and make the message more meaningful.

**Comment by FedeClaudi** [comment] 2018-11-02 08:57
Hi, thanks for your reply!

I don't think that the connection is lost as if I use `.fetch()` it works.
I tried restarting and I do have the latest version of datajoint. 

Is there anything else I can try?

**Comment by FedeClaudi** [comment] 2018-11-02 14:22
Minimum code to replicate the error (taken from the tutorials):

```
import datajoint as dj

schema = dj.schema('tutorial', locals())

@schema
class Mouse(dj.Manual):
      definition = """
      mouse_id: int                  # unique mouse id
      ---
      dob: date                      # mouse date of birth
      sex: enum('M', 'F', 'U')    # sex of mouse - Male, Female, or Unknown/Unclassified
      """

     m = Mouse()
    print(m)

```

The behaviour seems to be irregular: sometimes print(m) works:
```
print(m)
*mouse_id    dob     sex    
+----------+ +-----+ +-----+
```
But other times it doesn't:
```
print(m)
Out[6]: Traceback (most recent call last):
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\IPython\core\formatters.py", line 224, in catch_format_error
    r = method(self, *args, **kwargs)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\IPython\core\formatters.py", line 702, in __call__
    printer.pretty(obj)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\IPython\lib\pretty.py", line 402, in pretty
    return _repr_pprint(obj, self, cycle)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\IPython\lib\pretty.py", line 697, in _repr_pprint
    output = repr(obj)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\datajoint\query.py", line 357, in __repr__
    return super().__repr__() if config['loglevel'].lower() == 'debug' else self.preview()
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\datajoint\query.py", line 369, in preview
    tuples = rel.fetch(limit=limit+1)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\datajoint\fetch.py", line 59, in __call__
    cur = self._relation.cursor(as_dict=as_dict, limit=limit, offset=offset, order_by=order_by)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\datajoint\query.py", line 537, in cursor
    return self.connection.query(sql, as_dict=as_dict)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\datajoint\connection.py", line 136, in query
    cur.execute(query, args)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "C:\Users\Federico\Miniconda3\envs\CVenv\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
```


Once this error comes up, all subsequent calls to `print(m)` give the same error. Weirdly enough `fetch()` still works though.

**Comment by dimitri-yatsenko** [comment] 2018-11-02 15:44
I think it has to do with the server settings -- by default MySQL is poorly configured.  Will you please use the config file from https://github.com/datajoint/mysql-docker/blob/master/my.cnf or, for testing, get a tutorial account through  datajoint.io?

**Comment by FedeClaudi** [comment] 2018-11-02 17:30
I tried the tutorial server, re-installing the docker you've sent (I was already using that) and re installing MySQL + I check that MySQL is properly working following these instructions (https://blog.sqlauthority.com/2013/11/08/mysql-how-to-find-mysqld-exe-with-command-prompt-fix-mysql-is-not-recognized-as-an-internal-or-external-command-operable-program-or-batch-file/)

The error is still there unfortunately

**Comment by FedeClaudi** [comment] 2018-11-02 18:40
I will try to identify the query but I am not sure how. 
If it can help, setting ` "loglevel": "INFO"`, to` "loglevel": "DEBUG"` stops the bug from coming up, but of course one cannot preview the content of a table with that option. 

The weird behaviour seems to originate in `query.py` and in particular at line 356:
 ```
   def __repr__(self):
        return super().__repr__() if config['loglevel'].lower() == 'debug' else self.preview()

```
Three scenarios:
- if `config['loglevel'].lower() == 'debug'` -> no problem

- if `__repr__` is called by `print(m)` [and ` "loglevel": "INFO"`] then `self.preview()` is called an no error comes up

- but if `__repr__` is called by trying to display `m` directly in the PyCharm console, then the bug comes up in `__repr__ `but before getting into `self.preview()`  


This is not a huge problem as I can still populate query and fetch normally, but it does make setting up the database a bit more cumbersome as debugging becomes a bit harder. 

Thank you

**Comment by dimitri-yatsenko** [comment] 2018-11-02 18:58
Does `m.fetch(limit=13)` work?

**Comment by FedeClaudi** [comment] 2018-11-02 21:49
It does work, but print(m) breaks:

**Comment by dimitri-yatsenko** [comment] 2018-11-07 16:02
Are you at SfN by chance? -- we could try to debug it here.  I have tried to reproduce this error but no success yet. The error message does not seem to provide helpful information.

**Comment by FedeClaudi** [comment] 2018-11-07 16:08
Hi, no I'm not at SfN sorry!

**Comment by dimitri-yatsenko** [comment] 2018-11-17 21:56
Any progress on this?  @FedeClaudi  Would you mind running the tests in the tests folder?  I am still not able to reproduce this problem in my setup.

**Comment by FedeClaudi** [comment] 2018-11-19 12:48
Hi, I haven't had this bug coming up anymore, I think it might have to do with the fact that I switched from pycharm to vs code. The bug only happened while debugging in pycharm.

**Comment by dimitri-yatsenko** [comment] 2018-11-24 05:08
ok, should we close the issue then?  This may be specific to PyCharm on Windows.

**Comment by eywalker** [comment] 2018-12-02 14:38
@FedeClaudi This issue is likely due to the inconsistent state of the connection object that can be found while running under debugging mode. With PR #530, auto reconnect is triggered when the interface error is encountered, which can potentially "fix" this issue (at least make it possible to work during debugging mode). Once that PR is accepted, it would be great if you would test it under PyCharm debugging mode again. Thanks!

**Comment by dimitri-yatsenko** [comment] 2018-12-11 16:22
Please re-open if this becomes issue again.

**Closed by dimitri-yatsenko** 2018-12-11 16:22 UTC
Labels: question
