### ISSUE TITLE
Easier `argmax`

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#247] opened 2016-09-15 22:37 UTC
Currently finding a tuple with a column value equal to the maximum value of that column (`argmax`) is not easy at all. Given an example table below:

``` python
@schema
class Test(dj.Computed):
    definition="""
    key   :   int     # key
    ---
    value   :   int     # value
    """
    contents = [(k, k) for k in range(10)]
```

A suggested solution is to do

``` python
rel = Test()
rel * dj.U().aggregate(rel, vmax='max(value)') & 'value=vmax'
```

Aside from the fact that the above query currently doesn't work (refer to issue #246), the query is simply not intuitive even for an experienced user for an operation as simple as `argmax`. Of course you can do something like:

``` python
vmax = Test().fetch['value'].max()
Test() & ('value = %r' % vmax)
```

but it would be nice to be able to do this entirely in DataJoint.

**Comment by dimitri-yatsenko** [comment] 2016-09-15 22:53
The following will work even if it may defy some intuition.
```python
rel & dict(value=rel.proj('vmax=max(value)').fetch['vmax'])
```

Argmax is not untuititive in the relational model in general.  How about we define as a separate max method?
```python
rel & dict(value = rel.max['value'])     # restrict to value = max(value)   
```
This will require two transactions and complicates algebraic closure.  

We could have a separate restriction object `argmax` that would work like this:
```python
rel & dj.argmax('value')   # restrict to value=max(value)
```

**Comment by dimitri-yatsenko** [comment] 2016-09-15 22:55
Or even 
```python
rel.maximize('value')    #  restrict to value=max(value)    
```

**Comment by eywalker** [comment] 2016-09-15 22:57
I agree that whatever the solution we come up with, we should not break it into two separate queries. I'd have to think more as to what would be a good solution form.

**Comment by dimitri-yatsenko** [comment] 2016-09-15 23:03
the previous two solutions run in one query but are not general enough.

**Comment by dimitri-yatsenko** [comment] 2016-09-15 23:23
We can solve this by introducing two operators:
```python
rel.maximum('value')     # restricts to value=max(value)
``` 
and 
```python
rel.max(vmax='value')   
```
which is a relation comprising one tuple with one attribute `vmax`, which is the max value of `value`) 

For example, 
```python
Test()*Lookup().max(vmax='value') & 'param=vmax'   # all tests in which param = max value from Lookup
```

**Comment by dimitri-yatsenko** [comment] 2016-09-16 00:54
As designed now, after the bugfix, the syntax would be
```python
dj.U().aggregate(rel, vmax='max(value)') * rel & 'value=vmax'
```

**Comment by eywalker** [comment] 2016-09-20 19:32
Ok the suggested form sounds reasonable and I do like the flexibility. We will have to make sure that this gets documented very well and promoted into a list of useful tricks. We might want to start compiling FAQ like form of a page where users can quickly lookup frequently sought after manipulation/operations.

**Comment by dimitri-yatsenko** [comment] 2016-09-27 17:18
This has now been fixed and a test added in #251. 

To restrict to maximum value of field `value` in table `Test`, the query is:
```python
Test() & dj.U().aggregate(Test(), value='max(value)')
```

**Comment by dimitri-yatsenko** [comment] 2016-09-27 17:24
Please close this issue if you agree that it is resolved.

**Comment by eywalker** [comment] 2016-09-27 17:39
Let me verify the standing PR and I will subsequently close this issue.

**Comment by eywalker** [comment] 2016-10-03 21:49
PR #251 merged, fixing this issue. `argmax` can be now taken using

```python
Test() & dj.U().aggr(Test(), value='max(value)')
```

as @dimitri-yatsenko suggested. We'll properly document this.

**Comment by fabiansinz** [comment] 2018-01-12 14:23
This pattern does not work anymore in the latest datajoint version. The error message would be `DataJointError: Cannot join relations on dependent attribute value`. One fix could be to make `value` a primary key by joining it with `dj.U('value')`. However, that will break autopopulation if you use the armax pattern in a `key_source` because `autopopulate` now checks for primary keys. 

https://github.com/datajoint/datajoint-python/blob/0fffe1a0d6f76d055d4e1cfb6728b30b03fad282/datajoint/autopopulate.py#L77

**Comment by dimitri-yatsenko** [comment] 2018-01-16 16:22
Yes, the query should become
```python
(Test * dj.U('value')) & dj.U().aggr(Test, value='max(value)')
```

In this case, we are hampered by the way SQL implements aggregations.  Under the DataJoint model, the following syntax will make more sense and we will implement that sometime:
```python
Test & 'value=max(value)'
```

**Comment by dimitri-yatsenko** [comment] 2018-01-16 16:30
Actually, I think we should implement that now in this issue.  Currently, SQL does not allow aggregation functions in the WHERE clause.  The reason SQL does not allow them is because it is not clear what to group by but in DataJoint, that ambiguity does not exist.  We could detect aggregation operations and form the appropriate query.

**Comment by fabiansinz** [comment] 2018-01-16 16:50
I used the solution above, but the problem is that this will break autopopulation when you use that expression in a `key_source` since `populate` check for primary keys. Now `value` is a primary key that does not exist in the target which raises an error.

**Comment by dimitri-yatsenko** [comment] 2018-01-16 18:54
For release 0.11.0, I propose the following solution:  https://datajoint.blog/2018/01/16/aggregations-in-restrictions/

In the meantime, you can do
```python
key_value = Test & ((Test * dj.U('value')) & dj.U().aggr(Test, value='max(value)'))
```
Sorry.

**Comment by dimitri-yatsenko** [comment] 2018-01-16 19:01
After the solution described at https://datajoint.blog/2018/01/16/aggregations-in-restrictions/, the query will become 
```python
key_source = dj.U().aggr(Test, 'value=max(value)')
```
Its primary key will be empty but you can modify it as:
```python
key_source = dj.U('value') & dj.U().aggr(Test, 'value=max(value)')
```

**Comment by dimitri-yatsenko** [comment] 2018-01-16 22:10
sorry, we went down the wrong path.  We should change the query as follows
```python
key_source = Test * dj.U().aggr(Test, max_value='max(value)')) & 'value=max_value'
```
Sorry.

**Comment by dimitri-yatsenko** [comment] 2018-01-17 01:55
If this works, will you please close this issue?  I wrote a detailed explanation here https://datajoint.blog/2018/01/16/aggregations-in-restrictions/

**Comment by fabiansinz** [comment] 2018-01-17 03:13
Works. Thanks a lot. As a final comment: it's probably a lot faster to do 
`Test * dj.U().aggr(Test.proj('value'), max_value='max(value)') & 'value=max_value'` in many cases.

**Closed** 2018-01-17 03:14 UTC
Labels: enhancement
